# Desarrollo de modelos predictivos para la estimación de la temperatura superficial de los detectores del observatorio Pierre Auger




##  ** 1. Preparación de Datos **

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)


Definir nombres de las columnas que se van a usar y  la lista en la cual se van almacenar los dias de datos que se van a usar.

In [2]:
nombres2=['fLsId', 'fTime', 'fPMT[0]', 'fPMT[1]', 'fPMT[2]', 'fElectT',
       'fBatteryT[0]', 'fBatteryT[1]'] 
dias=[]

Cargar los dias de datos necesarios

In [3]:
dias.append(pd.read_csv("./0000mc_2017_08_01_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [4]:
dias.append(pd.read_csv("./0000mc_2017_08_02_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [5]:
dias.append(pd.read_csv("./0000mc_2017_08_04_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [6]:
dias.append(pd.read_csv("./0000mc_2017_08_05_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [7]:
dias.append(pd.read_csv("./0000mc_2017_08_07_00h09.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [8]:
dias.append(pd.read_csv("./0000mc_2017_08_08_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [9]:
dias.append(pd.read_csv("./0000mc_2017_08_09_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [10]:
dias.append(pd.read_csv("./0000mc_2017_08_10_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [11]:
dias.append(pd.read_csv("./0000mc_2017_08_12_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

In [12]:
dias.append(pd.read_csv("./0000mc_2017_08_13_00h00.root", header=None, names=nombres2, sep=" ", usecols=[0,1,14,15,16,17,18,19 ],index_col=1 ))

Se seleccionan en listas, los dias de datos de cada detector(los 19 mas cercanos a ** Los Leones **).

In [13]:
det321L=[]
det440L=[]
det322L=[]
det378L=[]
det384L=[]
det441L=[]
det427L=[]
det379L=[]
det361L=[]
det429L=[]
det433L=[]
det385L=[]
det367L=[]
det432L=[]
det387L=[]
det346L=[]
det364L=[]
det376L=[]
det375L=[]

for df in dias:
    df.index=pd.to_datetime(df.index,unit="s")
    det321L.append(df[df.fLsId==321])
    det440L.append(df[df.fLsId==440])
    det322L.append(df[df.fLsId==322])
    det378L.append(df[df.fLsId==378])
    det384L.append(df[df.fLsId==384])
    det441L.append(df[df.fLsId==441])
    det427L.append(df[df.fLsId==427])
    det379L.append(df[df.fLsId==379])
    det361L.append(df[df.fLsId==361])
    det429L.append(df[df.fLsId==429])
    det433L.append(df[df.fLsId==433])
    det385L.append(df[df.fLsId==385])
    det367L.append(df[df.fLsId==367])
    det432L.append(df[df.fLsId==432])
    det387L.append(df[df.fLsId==387])
    det346L.append(df[df.fLsId==346])
    det364L.append(df[df.fLsId==364])
    det376L.append(df[df.fLsId==376])
    det375L.append(df[df.fLsId==375])
    


Se seleccionan en listas, los dias de datos de cada detector(los 19 mas cercanos a ** Los Morados **).

In [14]:
det887L=[]
det878L=[]
det886L=[]
det879L=[]
det877L=[]
det881L=[]
det885L=[]
det876L=[]
det884L=[]
det888L=[]
det880L=[]
det882L=[]
det673L=[]
det908L=[]
det874L=[]
det893L=[]
det763L=[]
det883L=[]
det1175L=[]

for df in dias:
    df.index=pd.to_datetime(df.index,unit="s")
    det887L.append(df[df.fLsId==887])
    det878L.append(df[df.fLsId==878])
    det886L.append(df[df.fLsId==886])
    det879L.append(df[df.fLsId==879])
    det877L.append(df[df.fLsId==877])
    det881L.append(df[df.fLsId==881])
    det885L.append(df[df.fLsId==885])
    det876L.append(df[df.fLsId==876])
    det884L.append(df[df.fLsId==884])
    det888L.append(df[df.fLsId==888])
    det880L.append(df[df.fLsId==880])
    det882L.append(df[df.fLsId==882])
    det673L.append(df[df.fLsId==673])
    det908L.append(df[df.fLsId==908])
    det874L.append(df[df.fLsId==874])
    det893L.append(df[df.fLsId==893])
    det763L.append(df[df.fLsId==763])
    det883L.append(df[df.fLsId==883])
    det1175L.append(df[df.fLsId==1175])




Se seleccionan en listas, los dias de datos de cada detector(los 19 mas cercanos a ** Loma Amarilla **).

In [15]:
det1102L=[]
det1115L=[]
det1101L=[]
det1116L=[]
det1103L=[]
det1117L=[]
det1108L=[]
det1104L=[]
det1120L=[]
det1109L=[]
det1098L=[]
det1501L=[]
det1107L=[]
det1105L=[]
det1118L=[]
det1164L=[]
det1099L=[]
det1483L=[]
det1119L=[]

for df in dias:
        df.index=pd.to_datetime(df.index,unit="s")
        det1102L.append(df[df.fLsId==1102])
        det1115L.append(df[df.fLsId==1115])
        det1101L.append(df[df.fLsId==1101])
        det1116L.append(df[df.fLsId==1116])
        det1103L.append(df[df.fLsId==1103])
        det1117L.append(df[df.fLsId==1117])
        det1108L.append(df[df.fLsId==1108])
        det1104L.append(df[df.fLsId==1104])
        det1120L.append(df[df.fLsId==1120])
        det1109L.append(df[df.fLsId==1109])
        det1098L.append(df[df.fLsId==1098])
        det1501L.append(df[df.fLsId==1501])
        det1107L.append(df[df.fLsId==1107])
        det1105L.append(df[df.fLsId==1105])
        det1118L.append(df[df.fLsId==1118])
        det1164L.append(df[df.fLsId==1164])
        det1099L.append(df[df.fLsId==1099])
        det1483L.append(df[df.fLsId==1483])
        det1119L.append(df[df.fLsId==1119])



Se hace el remuestreo en aras de garantizar los 216 registros(1 registro cada 400 segundos) por dia y de esta manera, evitar que cada registro de cada detector corresponda con los registros de los otros.

La regla que se uso para hacer el remuestreo es el llenado hacia adelante, de modo que se no se usara informacion del futuro y asi seguir tratando los datos como una serie temporal. 

** Para los Leones **

In [16]:
det321=pd.concat(det321L).resample("400s").ffill()
det440=pd.concat(det440L).resample("400s").ffill()
det322=pd.concat(det322L).resample("400s").ffill()
det378=pd.concat(det378L).resample("400s").ffill()
det384=pd.concat(det384L).resample("400s").ffill()
det441=pd.concat(det441L).resample("400s").ffill()
det427=pd.concat(det427L).resample("400s").ffill()
det379=pd.concat(det379L).resample("400s").ffill()
det361=pd.concat(det361L).resample("400s").ffill()
det429=pd.concat(det429L).resample("400s").ffill()
det433=pd.concat(det433L).resample("400s").ffill()
det385=pd.concat(det385L).resample("400s").ffill()
det367=pd.concat(det367L).resample("400s").ffill()
det432=pd.concat(det432L).resample("400s").ffill()
det387=pd.concat(det387L).resample("400s").ffill()
det346=pd.concat(det346L).resample("400s").ffill()
det364=pd.concat(det364L).resample("400s").ffill()
det376=pd.concat(det376L).resample("400s").ffill()
det375=pd.concat(det375L).resample("400s").ffill()

** Para Los Morados **

In [17]:
det887=pd.concat(det887L).resample("400s").ffill()
det878=pd.concat(det878L).resample("400s").ffill()
det886=pd.concat(det886L).resample("400s").ffill()
det879=pd.concat(det879L).resample("400s").ffill()
det877=pd.concat(det877L).resample("400s").ffill()
det881=pd.concat(det881L).resample("400s").ffill()
det885=pd.concat(det885L).resample("400s").ffill()
det876=pd.concat(det876L).resample("400s").ffill()
det884=pd.concat(det884L).resample("400s").ffill()
det888=pd.concat(det888L).resample("400s").ffill()
det880=pd.concat(det880L).resample("400s").ffill()
det882=pd.concat(det882L).resample("400s").ffill()
det673=pd.concat(det673L).resample("400s").ffill()
det908=pd.concat(det908L).resample("400s").ffill()
det874=pd.concat(det874L).resample("400s").ffill()
det893=pd.concat(det893L).resample("400s").ffill()
det763=pd.concat(det763L).resample("400s").ffill()
det883=pd.concat(det883L).resample("400s").ffill()
det1175=pd.concat(det1175L).resample("400s").ffill()

** Para Loma Amarilla **

In [18]:
det1102=pd.concat(det1102L).resample("400s").ffill()
det1115=pd.concat(det1115L).resample("400s").ffill()
det1101=pd.concat(det1101L).resample("400s").ffill()
det1116=pd.concat(det1116L).resample("400s").ffill()
det1103=pd.concat(det1103L).resample("400s").ffill()
det1117=pd.concat(det1117L).resample("400s").ffill()
det1108=pd.concat(det1108L).resample("400s").ffill()
det1104=pd.concat(det1104L).resample("400s").ffill()
det1120=pd.concat(det1120L).resample("400s").ffill()
det1109=pd.concat(det1109L).resample("400s").ffill()
det1098=pd.concat(det1098L).resample("400s").ffill()
det1501=pd.concat(det1501L).resample("400s").ffill()
det1107=pd.concat(det1107L).resample("400s").ffill()
det1105=pd.concat(det1105L).resample("400s").ffill()
det1118=pd.concat(det1118L).resample("400s").ffill()
det1164=pd.concat(det1164L).resample("400s").ffill()
det1099=pd.concat(det1099L).resample("400s").ffill()
det1483=pd.concat(det1483L).resample("400s").ffill()
det1119=pd.concat(det1119L).resample("400s").ffill()

Se concatenan los datos de los detectores de forma horizontal.

In [19]:
#Leones
lista_Detec_leones=[det321,det440,det322, det378, det384,det441,det427,det379,det361,det429,det433,det385,det367,
             det432,det387,det346,det364,det376,det375]
detectoresLeones=pd.concat(lista_Detec_leones, axis=1)
detectoresLeones.drop("fLsId", axis=1, inplace=True) #Se borra todas las columnas con el nombre fLsId



#Morados
lista_Detec_losMorados=[det887, det878, det886,det879, det877,det881, det885,det876, det884, det888, det880, det882,
                       det673, det908, det874, det893,det763, det883, det1175 ]
detectoresMorados=pd.concat(lista_Detec_losMorados, axis=1)
detectoresMorados.drop("fLsId", axis=1, inplace=True) #Se borra todas las columnas con el nombre fLsId
#print(len(lista_Detec_losMorados))
print(detectoresMorados.shape)
print( detectoresLeones.shape)

#Loma Amarilla
lista_Detec_lomaAmarilla=[det1102, det1115, det1101,det1116,det1103,det1117,
      det1108,det1104,det1120,det1109,det1098,det1501,det1107,
      det1105,det1118,det1164,det1099,det1483,det1119]
detectoresLomaAmarilla=pd.concat(lista_Detec_lomaAmarilla, axis=1)
detectoresLomaAmarilla.drop("fLsId", axis=1, inplace=True) #Se borra todas las columnas con el nombre fLsId
print(detectoresLomaAmarilla.shape)

(2809, 114)
(2809, 114)
(2808, 114)


# Leer Temperatura de la estación

Se cargan  los datos de una estación, y se remuestrean de modo que correspondan con la frecuencia con las que se remuestrearon los datos de los detectores. De la misma manera que con los datos de los detectores, estos tambien se remuestrearon usando la regla de llenado hacia delante.

In [20]:
#Leones
nombres2=["Time","Temperature"]
temperature_Leones=pd.read_csv("/home/libardomm/auger/station/Los_Leones/wll_l2.dat", sep=" ", header=None, names=nombres2, usecols=[0, 1], index_col=None)
temperature_Leones.set_index("Time", inplace=True)
temperature_Leones.index=pd.to_datetime(temperature_Leones.index, unit="s")
temperature_Leones=temperature_Leones.resample("400s").ffill()


In [21]:
#Morados
nombres2=["Time","Temperature"]
temperature_Morados=pd.read_csv("/home/libardomm/auger/station/Los Morados/wlmo_l2.dat", sep=" ", header=None, names=nombres2, usecols=[0, 1], index_col=None)
temperature_Morados.set_index("Time", inplace=True)
temperature_Morados.index=pd.to_datetime(temperature_Morados.index, unit="s")
temperature_Morados=temperature_Morados.resample("400s").ffill()


In [22]:
#Loma Amarilla 
nombres2=["Time","Temperature"]
temperature_LomaAmarilla=pd.read_csv("/home/libardomm/auger/station/Loma_Amarilla/wlam_l2.dat", sep=" ", header=None, names=nombres2, usecols=[0, 1], index_col=None)
temperature_LomaAmarilla.set_index("Time", inplace=True)
temperature_LomaAmarilla.index=pd.to_datetime(temperature_LomaAmarilla.index, unit="s")
temperature_LomaAmarilla=temperature_LomaAmarilla.resample("400s").ffill()




Se toman solamente los registros de temperatura necesarios para que coincidan con el numero de registros que se tomaron en los detectores. 

In [23]:
#Leones
first=str(detectoresLeones.index[0])
last=str(detectoresLeones.index[-1])
temperature_Leones=temperature_Leones.loc[first:last]


#Morados
first=str(detectoresMorados.index[0])
last=str(detectoresMorados.index[-1])
temp=temperature_Morados.loc[first:last]
temperature_Morados.loc[first]

In [27]:
#LomaAmarilla
first=str(detectoresLomaAmarilla.index[0])
last=str(detectoresLomaAmarilla.index[-1])
temperature_LomaAmarilla=temperature_LomaAmarilla.loc[first:last]


Se concatena la temperatura de la estacion con los datos de los detectores. Tambien se eliminan manualmente las filas de datos de los dias faltantes como tambien la primera fila que tiene datos anterioresl al primer dia

In [28]:
def preparadordeDatos(detectores_station, temp):
    data_station=pd.concat([detectores_station, temp], axis=1)
    data_station.drop(data_station.loc["2017-07-31"].index, inplace=True)
    data_station.drop(data_station.loc["2017-08-03"].index, inplace=True)
    data_station.drop(data_station.loc["2017-08-06"].index, inplace=True)
    data_station.drop(data_station.loc["2017-08-11"].index, inplace=True) 
    data_station.fillna(method="ffill", inplace=True)
    data_station.fillna(method="bfill", inplace=True)

    return data_station

In [29]:
data_loslones= preparadordeDatos(detectoresLeones,temperature_Leones)
data_lomaAmarilla=preparadordeDatos(detectoresLomaAmarilla,temperature_LomaAmarilla)
print(data_loslones.shape)
print(data_lomaAmarilla.shape)

(2160, 115)
(2159, 115)


In [30]:
data_lomaAmarilla[data_lomaAmarilla.iloc[:,110].isnull()]
#data_lomaAmarilla.iloc[:,110].isnull().sum()

Empty DataFrame
Columns: [fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, fBatteryT[0], fBatteryT[1], fPMT[0], fPMT[1], fPMT[2], fElectT, ...]
Index: []

## 2. Machine Learning

In [31]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import  metrics

Se define cual va a ser la matriz de variables de entrada( X: datos de tanques) y el vector con los datos deseados (y: temperatura de una estacion)

In [66]:
def XySplit(data_station):
    columnas=[ 'fPMT[0]', 'fPMT[1]', 'fPMT[2]', 'fElectT',
       'fBatteryT[0]', 'fBatteryT[1]'] 
    
    X=data_station[columnas]
    y=data_station.Temperature
    return X,y

In [67]:
columnas=data_lomaAmarilla.columns.tolist()
columnas.remove("Temperature")
len(columnas)
#X=data_lomaAmarilla.iloc[:,1:130]
#X[columnas]

114

In [68]:
X, y=XySplit(data_lomaAmarilla)
print(X.shape)
print(y.shape)

(2159, 114)
(2159,)


Se define la funcion que va a permitir cortar el datos segun las estrategia que se describe a continuacion: 
* En la primera configuracion se toma algunos dias de datos consecutivos como datos de training y el dia imediatamente despues al ultimo de los dia de training se toma como test.
* En la siguiente configuracion se corren tanto los datos de training como los de test en un dia. O en otras palabras, si se toman tres dias de training y en la anterior configuracion se tomaron los dias 1,2 y 3 como training y el dia 4 como testing, en este caso se toman los dias 2,3,4 como training y el dia 5 como testing.

In [69]:
linreg=LinearRegression()

def cross_val( Trainfolds, datos, target):
    
    n=int(X.shape[0]/216)-Trainfolds
    linreg=LinearRegression()
    regs=216
    errores=[]

    for n in range(0,n):
        f_day_n= regs*n #primer dia de entrenamiento
        l_day_n=f_day_n + (Trainfolds*regs) #ultimo dia de entrenan
        iX_train=datos.iloc[f_day_n:l_day_n]
        iX_test= datos.iloc[l_day_n: l_day_n+regs]
        
        iy_train=target.iloc[f_day_n:l_day_n]
        iy_test=target.iloc[l_day_n: l_day_n+regs]
        
        linreg.fit(iX_train,iy_train)
        iy_predic=linreg.predict(iX_test)
        errores.append(np.sqrt(metrics.mean_squared_error(iy_test,iy_predic)))
    return  np.array([np.mean(errores),np.std(errores)])
    #print("Media de errores", np.mean(errores))
    #print("Desviacion estandar", np.std(errores))

In [70]:
cross_val(3,X,y)

array([ 2.61808611,  0.84744754])

In [71]:
cross_val(4,X,y)

array([ 2.16862923,  0.54609   ])

In [72]:
cross_val(5, X,y)

array([ 1.61243966,  0.21162993])

In [74]:
tabla=np.array([0,0])
#tabla=np.append([[0,0]],[[1,2]], axis=0)
tabla=np.append([tabla],[[1,2]], axis=0)
#tabla=np.append([tabla],[[1,3]], axis=0)
tabla=np.vstack([tabla,[3,5]])
tabla
#np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]],axis=0)

array([[0, 0],
       [1, 2],
       [3, 5]])

In [75]:
#tab=np.zeros([2])
tab=np.array(["mean","standar dev"])
for i in range(3,6):
    a=cross_val(i,X,y)
    a[0]
    tab=np.vstack([tab,cross_val(i,X,y)])
tab

array([['mean', 'standar dev'],
       ['2.6180861124216714', '0.8474475374145886'],
       ['2.168629233139874', '0.5460899965951301'],
       ['1.6124396615414636', '0.21162992527686872']],
      dtype='<U32')

In [120]:
#indices = ["3d-1d-L","4d-1d-L","5d-1d-L","3d-1d-A","4d-1d-A","5d-1d-A","3d-1d-M","4d-1d-M","5d-1d-M"]
indices = ["3d-1d-L","4d-1d-L","5d-1d-L","3d-1d-A","4d-1d-A","5d-1d-A"]

In [123]:
#dati=pd.DataFrame(data=[1,2], columns=["Mean", "Standard Deviation"])
my_df= []

data_station_list = [data_loslones, data_lomaAmarilla]
for data in data_station_list:
    X,y  = XySplit(data)

    for i in range(3,6):
        a=cross_val(i,X,y)
        d = {
            'Mean' : a[0] , # some formula for obtaining values
            'Standard Dev' : a[1],
        }
        my_df.append(d)

my_df = pd.DataFrame(my_df)

my_df.set_index([indices])

Mean  Standard Dev
3d-1d-L  2.391302      0.946855
4d-1d-L  2.031739      0.745023
5d-1d-L  1.608492      0.596830
3d-1d-A  2.618086      0.847448
4d-1d-A  2.168629      0.546090
5d-1d-A  1.612440      0.211630

In [119]:
my_df

Mean  Standard Dev
0  2.391302      0.946855
1  2.031739      0.745023
2  1.608492      0.596830
3  2.618086      0.847448
4  2.168629      0.546090
5  1.612440      0.211630

In [131]:
# manden un vector
def linearDavid(data_station_list): 
    my_df= []
    for data in data_station_list:
        X,y  = XySplit(data)

        for i in range(3,6):
            a=cross_val(i,X,y)
            d = {
                'Mean' : a[0] , # some formula for obtaining values
                'Standard Dev' : a[1],
            }
            my_df.append(d)

    my_df = pd.DataFrame(my_df)

    #my_df.set_index([indices])
    
    return my_df
    

In [ ]:
indices = ["3d-1d-L","4d-1d-L","5d-1d-L","3d-1d-A","4d-1d-A","5d-1d-A"]
def creameIndice(i):
    

In [132]:
linearDavid(data_station_list)

Mean  Standard Dev
0  2.489760      0.988989
1  2.132016      0.778293
2  1.569130      0.661446
3  2.618086      0.847448
4  2.168629      0.546090
5  1.612440      0.211630